# Import libraray

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sns.set(style='whitegrid',palette='Set2',font_scale=1.1)
pd.set_option("display.float_format","{:2f}".format)

# Import Dataset

In [3]:
df = pd.read_csv("../01_data/spam.csv",encoding="latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [4]:
df.shape

(5572, 5)

# Data Cleaning

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [6]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

Observation : Most of values missing in columns 'Unnamed: 2' , 'Unnamed: 3', 'Unnamed: 4'           
So we Drop the columns

In [7]:
# drop last 3 columns
df.drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],inplace = True)

Columns names are not Description       
rename the columns

In [8]:
df.rename(columns= {
    'v1': 'target',
    'v2': 'text'
},inplace = True)

In [9]:
df.sample(5)

     target                                               text
4902    ham               \I;m reaching in another 2 stops.\""
410     ham  Come by our room at some point so we can iron ...
340     ham                       Ok that's great thanx a lot.
3651    ham     Probably not, still going over some stuff here
2574   spam  Your next amazing xxx PICSFREE1 video will be ...

Using label Encoding  Convert Categorical target --> Numbers

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit_transform(df['target'])

array([0, 0, 1, ..., 0, 0, 0])

In [12]:
df['target'] = encoder.fit_transform(df['target'])

In [14]:
df.sample(5)

      target                                               text
2610       0     As usual..iam fine, happy &amp; doing well..:)
4029       0                       Cool, I'll text you in a few
919        0              Dont talk to him ever ok its my word.
1766       1  SMS AUCTION You have won a Nokia 7250i. This i...
4464       0  \CHEERS FOR CALLIN BABE.SOZI CULDNT TALKBUT I ...

In [15]:
# check missing values
df.isna().sum()

target    0
text      0
dtype: int64

In [16]:
# check duplicate values 
df.duplicated().sum()

403

In [19]:
# remove duplicates
df.drop_duplicates(keep='first',inplace=True)

In [20]:
df

      target                                               text
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5567       1  This is the 2nd time we have tried 2 contact u...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [21]:
df.shape

(5169, 2)